# Generated by Django 3.1.7 on 2021-04-18 07:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid Group name', message='Group name must be alphanumeric, may contain - or _', regex='^[a-zA-Z0-9_-]{3,50}$')])),
                ('group_info', models.CharField(blank=True, max_length=300, null=True)),
                ('group_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_created', to=settings.AUTH_USER_MODEL)),
                ('group_members', models.ManyToManyField(related_name='all_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
