# Generated by Django 3.1.7 on 2021-04-23 07:25

import chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('message_datetime', models.DateTimeField(auto_now_add=True, verbose_name='date posted')),
                ('is_notice', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=models.SET(chat.models.get_del_user), to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.group')),
            ],
        ),
    ]
