# Generated by Django 3.1.7 on 2021-04-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_creater',
            new_name='is_creator',
        ),
    ]
